Models/Admin.cs
namespace LaundryReservationSystem.Models
{
    public class Admin

    {
        public int Id { get; set; }
        public string AdminName { get; set; }
        public string AdminSurame { get; set; }
        public string AdminPhone { get; set; }
        public string AdminPassword { get; set; }
        public string AdminCode { get; set; }

    }
}

Models/AppDbContext.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LaundryReservationSystem.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Admin> Admins { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Machine> Machines { get; set; }
        public DbSet<Booking> Bookings { get; set; }
    }
}

Models/Booking.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace LaundryReservationSystem.Models
{
    public class Booking
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPhone { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime BookingDate { get; set; }
        public TimeSpan BookingTimeStart { get; set; }
        public string MachineType { get; set; }
        public int MachineNumber { get; set; }


        

    }
}

Models/ErrorViewModel.cs
namespace LaundryReservationSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Machine.cs
namespace LaundryReservationSystem.Models
{
    public class Machine
    {
        public int Id { get; set; }

        public string MachineType { get; set; }

        public int MachineNumber { get; set; }

        public bool IsRunning { get; set; }

        public bool isFaulty { get; set; }

    }
}

Models/User.cs
namespace LaundryReservationSystem.Models
{
    public class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPhone { get; set; }
        public string UserPassword { get; set; }
    }
}

Controllers/AdminPageController.cs
using LaundryReservationSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LaundryReservationSystem.Controllers
{
    public class AdminPageController : Controller
    {
        private readonly AppDbContext _dbContext;
        public AdminPageController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CheckPhoneNumber(string phoneNumber)
        {
            var existingUser = _dbContext.Users.FirstOrDefault(u => u.UserPhone == phoneNumber);
            return Json(new { exists = existingUser != null });
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            var users = _dbContext.Users.ToList();
            ViewBag.UsersInfo = users;


            return View();
        }

        [HttpPost]
        public IActionResult AddUser(User newUser)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    _dbContext.Users.Add(newUser);
                    _dbContext.SaveChanges();

                    return RedirectToAction("AddUser");
                }
                else
                {
                    TempData["ErrorMessage"] = "Invalid inputs, please check your information.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred, please try again.";
            }

            return View(newUser);
        }

        [HttpPost]
        public IActionResult DeleteUser(User userD)
        {
            var user = _dbContext.Users.Find(userD.Id);
            if (user != null)
            {
                _dbContext.Users.Remove(user);
                _dbContext.SaveChanges();

                return RedirectToAction("AddUser");
            }

            return RedirectToAction("AddUser");
        }


    }
}

Controllers/BookingController.cs
using LaundryReservationSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace LaundryReservationSystem.Controllers
{
    public class BookingController : Controller
    {

        private readonly AppDbContext _dbContext;
        public BookingController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public ActionResult Index()
        {
            return View();
        }
        

        [HttpGet]
        public IActionResult GetAvailableMachines(DateTime date, TimeSpan startTime, string machineType)
        {

            var reservedMachines = _dbContext.Bookings
                .Where(b => b.BookingDate == date &&
                            b.BookingTimeStart == startTime &&
                        b.MachineType == machineType)
                .Select(b => b.MachineNumber)
                .ToList();

            var allMachines = _dbContext.Machines
                .Where(m => m.MachineType == machineType && m.isFaulty == false)
                .Select(m => m.MachineNumber)
                .ToList();

            var availableMachines = allMachines.Except(reservedMachines).ToList();

            return Json(availableMachines);
        }


        [HttpGet]
        public ActionResult Create()
        {
            var machineTypes = _dbContext.Machines.Select(m => m.MachineType).Distinct().ToList();

            ViewBag.MachineType = machineTypes;

          
            return View();
        }

        [HttpPost]
        public ActionResult Create(Booking newBooking)
        {           
           
            try
            {
                if (ModelState.IsValid)
                {
                    _dbContext.Bookings.Add(newBooking);
                    
                    _dbContext.SaveChanges();

                    TempData["SuccessMessage"] = "Reservation has been successfully saved.";

                    return RedirectToAction("Create");
                }
                else
                {
                    TempData["ErrorMessage"] = "Reservation could not be saved. Please check your inputs.";

                    return View(newBooking);
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        private ActionResult RedirectToAction(Func<ActionResult> ındex)
        {
            throw new NotImplementedException();
        }
      
    }
}

Controllers/HomeController.cs
using LaundryReservationSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LaundryReservationSystem.Controllers
{
    public class HomeController : Controller
    {

        private readonly AppDbContext _dbContext;
        public HomeController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var bookings = _dbContext.Bookings.ToList();
            ViewBag.BookingsInfo = bookings;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AdminPage/AddUser.cshtml
@model LaundryReservationSystem.Models.User


<h1>Add User</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUser">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="UserName" class="control-label">Name:</label>
                <input type="text" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserSurname" class="control-label">Surname:</label>
                <input type="text" asp-for="UserSurname" class="form-control" />
                <span asp-validation-for="UserSurname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserPhone" class="control-label">Phone:</label>
                <input type="text" asp-for="UserPhone" pattern="[0-9]+" class="form-control" />
                <span asp-validation-for="UserPhone" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="UserPassword" class="control-label">Password:</label>
                <input type="text" asp-for="UserPassword" class="form-control" />
                <span asp-validation-for="UserPassword" class="text-danger"></span>
            </div>


                <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>

<h2>Users</h2>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Phone</th>
            <th>Password</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in ViewBag.UsersInfo)
        {
            <tr>
                <td>@user.UserName</td>
                <td>@user.UserSurname</td>
                <td>@user.UserPhone</td>
                <td>@user.UserPassword</td>
                <td> 
                    <form method="post" asp-action="DeleteUser" asp-controller="AdminPage">
                    <input type="hidden" name="Id" value="@user.Id" />
                    <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            
        }
    </tbody>
</table>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>

$('#UserPhone').on('blur', function () {
    var phoneNumber = $("#UserPhone").val();
    $.ajax({
        url: '/AdminPage/CheckPhoneNumber',
        type: 'GET',
        data: { phoneNumber: phoneNumber },
        success: function (result) {
            if (result.exists) {
                        $('#phone-error').text("This phone number is already in use.");
            } else {
                $('#phone-error').text("");
            }
        }
    });
});
 </script>
}

Views/Booking/Create.cshtml
@model LaundryReservationSystem.Models.Booking

<h1>CreateBooking</h1>

<h4>Booking</h4>
<hr />

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="UserName" class="control-label">Name:</label>
                <input type="text" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserSurname" class="control-label">Surname:</label>
                <input type="text" asp-for="UserSurname" class="form-control" />
                <span asp-validation-for="UserSurname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserPhone" class="control-label">Phone:</label>
                <input type="text" asp-for="UserPhone" pattern="[0-9]+" class="form-control" />
                <span asp-validation-for="UserPhone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="BookingDate" class="control-label">Booking Date:</label>
                <input type="date" asp-for="BookingDate" class="form-control" />
                <span asp-validation-for="BookingDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
           
            <label asp-for="BookingTimeStart" class="control-label">Booking Time:</label>
            <select asp-for="BookingTimeStart" class="form-control">
                @for (int hour = 7; hour < 24; hour++)
                {
                    <option value="@hour:00">@hour:00</option>
                }
            </select>



            <div class="form-group">
                <label asp-for="MachineType" class="c-label">Machine Type:</label>
                <select asp-for="MachineType" class="form-control" id="MachineType">
                    <option value="">Select Machine Type</option>
                    @foreach (var type in ViewBag.MachineType)
                    {
                        <option value="@type">@type</option>
                    }
                </select>
                <span asp-validation-for="MachineType" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="MachineNumber" class="control-label">Machine Number:</label>
                <select asp-for="MachineNumber" class="form-control" id="MachineNumber"></select>
                <span asp-validation-for="MachineNumber" class="text-danger"></span>
            </div>



            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(function () {
            $('#BookingDate, #BookingTime, #MachineType').change(function () {
                var date = $('#BookingDate').val();
                var startTime = $('#BookingTimeStart').val();
                var machineType = $('#MachineType').val();

                $.ajax({
                    url: '/Booking/GetAvailableMachines',
                    type: 'GET',
                    data: { date: date, startTime: startTime, machineType: machineType },
                    success: function (result) {
                        var options = '';
                        $.each(result, function (index, value) {
                            options += '<option value="' + value + '">' + value + '</option>';
                        });
                        $('#MachineNumber').html(options);
                    }
                });
            });
        });

        $(function () {
             $('#bookingDate').change(function () {
                 var selectedDate = new Date($(this).val());
                  if (selectedDate <= new Date()) {
                    selectedDate = new Date();
                }
                $('#bookingTime').empty();
                for (var hour = selectedDate.getHours(); hour < 24; hour++) {
                    $('#bookingTime').append($('<option>', {
                        value: hour + ':00',
                        text: hour + ':00'
                    }));
                }
            });
        });

    </script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Booking Page";
}

<head>
    <meta charset="UTF-8">
    <title>Laundry Reservations</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <div class="container">

        <header>
            <h1>Laundry Reservations</h1>
        </header>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Phone</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Machine Type</th>
                    <th>Machine Number</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var booking in ViewBag.BookingsInfo)
                {
                    <tr>
                        <td>@booking.UserName</td>
                        <td>@booking.UserSurname</td>
                        <td>@booking.UserPhone</td>
                        <td>@booking.BookingDate.ToString("yyyy-MM-dd")</td>
                        <td>@booking.BookingTimeStart</td>
                        <td>@booking.MachineType</td>
                        <td>@booking.MachineNumber</td>
                    </tr>

                }
            </tbody>
        </table>



    </div>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaundryReservationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LaundryReservationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LaundryReservationSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Create">Booking</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminPage" asp-action="AddUser">Add User</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LaundryReservationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>